### ISSUE TITLE
[Question] transform snake to camel case

### ISSUE THREAD

**Issue by wongsitu** [astahmer/openapi-zod-client#46] opened 2022-12-01 21:32 UTC
I have an external API with a yaml Schema that has all fields in snake case. Is there a way to transform the generated schemas from snake to camel case?

**Comment by astahmer** [comment] 2022-12-01 21:35
hey, could you share an example (minimal reproduction) of your current input and an example of what you would like as output ?

**Comment by wongsitu** [comment] 2022-12-02 00:36
Sure! for example, I'd like to generate my zod schemas with tagId to instead of tag_id

`openapi: "3.0.0"
info:
    version: 1.0.0
    title: Swagger Petstore
    license:
        name: MIT
servers:
    - url: http://petstore.swagger.io/v1
paths:
    /pets:
        get:
            summary: List all pets
            operationId: listPets
            tags:
                - pets
            parameters:
                - name: limit
                  in: query
                  description: How many items to return at one time (max 100)
                  required: false
                  schema:
                      type: integer
                      format: int32
            responses:
                "200":
                    description: A paged array of pets
                    headers:
                        x-next:
                            description: A link to the next page of responses
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Pets"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
        post:
            summary: Create a pet
            operationId: createPets
            tags:
                - pets
            responses:
                "201":
                    description: Null response
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
    /pets/{petId}:
        get:
            summary: Info for a specific pet
            operationId: showPetById
            tags:
                - pets
            parameters:
                - name: pet_id
                  in: path
                  required: true
                  description: The id of the pet to retrieve
                  schema:
                      type: string
            responses:
                "200":
                    description: Expected response to a valid request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Pet"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
components:
    schemas:
        Pet:
            type: object
            required:
                - id
                - name
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                tag_id:
                    type: string
        Pets:
            type: array
            items:
                $ref: "#/components/schemas/Pet"
        Error:
            type: object
            required:
                - location_id
                - message
            properties:
                location_id:
                    type: integer
                    format: int32
                message:
                    type: string`

`import { makeApi, Zodios } from "@zodios/core";
import { z } from "zod";

const Pet = z.object({
  id: z.number().int(),
  name: z.string(),
  tag_id: z.string().optional(),
});
const Pets = z.array(Pet);
const Error = z.object({ location_id: z.number().int(), message: z.string() });

const endpoints = makeApi([
  {
    method: "get",
    path: "/pets",
    requestFormat: "json",
    parameters: [
      {
        name: "limit",
        type: "Query",
        schema: z.number().int().optional(),
      },
    ],
    response: z.array(Pet),
  },
  {
    method: "post",
    path: "/pets",
    requestFormat: "json",
    response: z.void(),
  },
  {
    method: "get",
    path: "/pets/:petId",
    requestFormat: "json",
    parameters: [
      {
        name: "pet_id",
        type: "Path",
        schema: z.string(),
      },
    ],
    response: Pet,
  },
]);

export const api = new Zodios(endpoints);
`

**Comment by astahmer** [comment] 2022-12-02 09:19
ok so just to be sure, the only change would be here ?

```
const Pet = z.object({
  id: z.number().int(),
  name: z.string(),
// current
//  tag_id: z.string().optional(),
//  ^^^^^
// what you want:
  tagId: z.string().optional(),
// ^^^
});
```

- wouldn't that produce an api client expecting wrongly named properties ? expecting `tagId` whereas the API actually sends `tag_id`
would not this lead to unexpected errors ?

- or is the input OpenAPI document wrong ? generating properties with `tag_id` whereas the API actually sends `tagId` ?
but then would not it make more sense to just fix the generated open api document ?


anyway, atm there is no such feature (some kind of hook/option to allow renaming a prop) in the generator itself.
however, I guess you could achieve that with a custom handlebars template (using the appropriate `openapi-zod-client` option) and using a [custom helper function](https://handlebarsjs.com/api-reference/helpers.html#the-options-parameter) with would use a snakeToCamelFn

**Comment by wongsitu** [comment] 2022-12-02 22:41
I'm using an axios interceptor to format API responses. But yeah, you're right, there's no point in including that parsing functionality into the CLI.  Could you please provide an example of how to use custom helpers? I've been digging around the docs with no success. I'm not sure exactly where to declare my helper function. Here's what I got. Am I doing something wrong?

```
// camelCase.ts
import Handlebars from 'handlebars';

Handlebars.registerHelper('camelCase', (object) => {
  // Do stuff here
});
```
```
// template.hbs
import { makeApi, Zodios } from "@zodios/core";
import { z } from "zod";

{{#if imports}}
{{#each imports}}
import { {{{@key}}} } from "./{{{this}}}"
{{/each}}
{{/if}}

{{#if types}}
{{#each types}}
{{{this}}};
{{/each}}
{{/if}}

{{#each schemas}}
export const {{@key}}{{#if (lookup ../circularTypeByName @key)}}: z.ZodType<{{@key}}>{{/if}} = {{{ lookup ./camelCase this}}};
{{/each}}
...
```

**Comment by astahmer** [comment] 2022-12-02 22:58
i'm no expert in handlebars 😅  but this looks fine 

ideally you should just be using the [`generateZodClientFromOpenAPI`](https://github.com/astahmer/openapi-zod-client/blob/main/lib/src/generateZodClientFromOpenAPI.ts) function to make your own CLI (or use it programmatically), but as of now there is no way to customize the handlebars instance (it recreates one everytime)

so, currently if you want it to work you'd need to more or less c/c the content of that function and yes, add a helper like you did
but i'm thinking this could be nice for everyone to have the possibility to pass your own custom handlebars instance to `generateZodClientFromOpenAPI` (so you wouldn't need to c/c its content..), would that be ok for you ?

**Comment by wongsitu** [comment] 2022-12-02 23:10
Yeah, that sounds great! 🥳

**Comment by astahmer** [comment] 2022-12-02 23:19
ok it's done & published in v1.4.3 !
you can use the `getHandlebars` provided to get an instance of handlebars preconfigured with "ifeq" helper (used in default template)

related commit: https://github.com/astahmer/openapi-zod-client/commit/3675691cc7f3f5ac70299f6be1b60c8b7ba88598

**Comment by wongsitu** [comment] 2022-12-04 01:22
Hi! a couple of difficulties here. I manage to register a handlebar in the instance, but for some reason, it's not working on the template Here's my CLI file:

```
// generator.ts
import SwaggerParser from '@apidevtools/swagger-parser';
import type { OpenAPIObject } from 'openapi3-ts';
import { generateZodClientFromOpenAPI, getHandlebars } from 'openapi-zod-client';
import { camelizeKeys } from 'humps';
import { resolveConfig } from 'prettier';

const main = async () => {
  const Handlebars = getHandlebars();

  Handlebars.registerHelper('snakeToCamelFn', (obj: object) => camelizeKeys(obj));
  const openApiDoc = (await SwaggerParser.parse('src/api.yaml')) as OpenAPIObject;
  const prettierConfig = await resolveConfig('./');
  const result = await generateZodClientFromOpenAPI({
    openApiDoc,
    distPath: 'src/api.ts',
    prettierConfig,
    templatePath: 'src/template.hbs',
  });

  console.log(Handlebars);
};

main();
```
It seems to log correctly:
```
HandlebarsEnvironment {
  helpers: {
    blockHelperMissing: [Function (anonymous)],
    each: [Function (anonymous)],
    helperMissing: [Function (anonymous)],
    if: [Function (anonymous)],
    unless: [Function (anonymous)],
    log: [Function (anonymous)],
    lookup: [Function (anonymous)],
    with: [Function (anonymous)],
    ifeq: [Function (anonymous)],
    snakeToCamelFn: [Function (anonymous)]
  },
  partials: {},
  decorators: { inline: [Function (anonymous)] },
  __esModule: true,
  HandlebarsEnvironment: [Function: HandlebarsEnvironment],
....
```
But when I use it in my template: 
```
//template.hbs
import { makeApi, Zodios } from "@zodios/core";
import { z } from "zod";

{{#if imports}}
{{#each imports}}
import { {{{@key}}} } from "./{{{this}}}"
{{/each}}
{{/if}}

{{#if types}}
{{#each types}}
{{{this}}};
{{/each}}
{{/if}}

{{#each schemas}}
export const {{@key}}{{#if (lookup ../circularTypeByName @key)}}: z.ZodType<{{@key}}>{{/if}} = {{{snakeToCamelFn this}}};
{{/each}}
```
It throws this error:
```
Error: Missing helper: "snakeToCamelFn"
```
Am I missing something?

Also, the getHandlebars function, returns type any 😢 
![image](https://user-images.githubusercontent.com/21975542/205469464-073516c0-e97d-438c-aa96-4e4766d699d7.png)

**Comment by astahmer** [comment] 2022-12-04 11:50
Ahh, well first it looks like you forgot to pass your custom handlebars instance to `generateZodClientFromOpenAPI` like:
```ts
const result = await generateZodClientFromOpenAPI({
        openApiDoc,
        distPath: "./snake.ts",
        templatePath: "./snake-template.hbs",
        handlebars: Handlebars,
    });
```

but on a second thought, while doable, this will be very tedious since you're not receiving an object here 
```ts
Handlebars.registerHelper('snakeToCamelFn', (obj: object) => camelizeKeys(obj));
                                                                               ^^^^^^^^^
```

but actually a zod schema string (the output) like:
```ts
Handlebars.registerHelper('snakeToCamelFn', (schema: string) => console.log(schema);
                                                                               ^^^^^^^^^
```

**Comment by wongsitu** [comment] 2022-12-04 18:34
I think this might just work 😅:
```
type CamelizeString<T extends PropertyKey, C extends string = ''> = T extends string
  ? string extends T
    ? string
    : T extends `${infer F}_${infer R}`
    ? CamelizeString<Capitalize<R>, `${C}${F}`>
    : `${C}${T}`
  : T;

type Camelize<T> = {
  [K in keyof T as CamelizeString<string & K>]: T[K] extends Array<infer U>
    ? U extends {}
      ? Array<Camelize<U>>
      : T[K]
    : T[K] extends {}
    ? Camelize<T[K]>
    : T[K];
};
```
```
import SwaggerParser from '@apidevtools/swagger-parser';
import type { OpenAPIObject } from 'openapi3-ts';
import { generateZodClientFromOpenAPI, getHandlebars } from 'openapi-zod-client';
import { resolveConfig } from 'prettier';

const main = async () => {
  const Handlebars = getHandlebars();
  const openApiDoc = (await SwaggerParser.parse('src/api.yaml')) as OpenAPIObject;
  const prettierConfig = await resolveConfig('./');

  Handlebars.registerHelper(
    'snakeToCamelFn',
    (zodSchema: string) => `${zodSchema}.transform((input) => camelizeKeys(input) as Camelize<typeof input>)`,
  );

  const result = await generateZodClientFromOpenAPI({
    openApiDoc,
    distPath: 'src/api.ts',
    prettierConfig,
    templatePath: 'src/template.hbs',
    handlebars: Handlebars,
  });

  console.log(result);
};

main();
```
Only problem here `generateZodClientFromOpenAPI` is not taking handlebars as argument 😢 :
![image](https://user-images.githubusercontent.com/21975542/205508875-fe7c5bb5-fea9-4846-8d2f-e42a78c21c20.png)
![image](https://user-images.githubusercontent.com/21975542/205508789-b9ecf5c3-0aad-49fa-941f-c3269644e952.png)

**Comment by astahmer** [comment] 2022-12-04 18:56
> Only problem here generateZodClientFromOpenAPI is not taking handlebars as argument 😢 :

oops sorry, just published & fixed in 1.4.4

**Comment by wongsitu** [comment] 2022-12-04 19:06
Much appreciated! It's working now. Thanks. 🚀

**Comment by robotkutya** [comment] 2022-12-08 09:34
Awesome seeing this project going forward! <3

It solves a very important and pretty common pain point --> when you don't have control over the backend, or it's in another language, etc.

Can I have a small request? It would be great to have a changelog for releases. I am trying to keep up with this library, as it became a core part of our stack, but currently, I have to go over commits manually to catch up.

Also, what's the state of accepting contributions? I might get some time during the holidays. Are these open for contribution?

**Comment by robotkutya** [comment] 2022-12-09 11:16
> very open to contributions !
> is there anything specific you need ?

Awesome! :)
Some recommendations for easier / first issues would be helpful to get me started.

**Comment by astahmer** [comment] 2022-12-09 17:22
ahh i'm sorry I wasnt clear, I meant what would you need as features that is currently missing from `openapi-zod-client` ? I could then maybe direct you at some parts of the codebase that would be related or helpful for an implementation of those features

i'm sure there are features missing but I probably haven't seen those use cases yet so I wouldn't know what to recommend you to take a look at 😭 

from a quick look in the issues+codebase, I found:
- I guess there is the [CI issue](https://github.com/astahmer/openapi-zod-client/issues/48) (changelog + readme missing)
- some missing tests for the last patches https://github.com/astahmer/openapi-zod-client/issues/47
- [handling aliases starting by a number](https://github.com/astahmer/openapi-zod-client/blob/42100d199a1168dcb9e54317d2ae5a11bdc1b880/lib/tests/name-starting-with-number.test.ts#L43), since a method's name can not start with a number so the generated api.123() would not work and should be prefixed by a `_` so it can be called like this: `api._123()`
- [maybe output z.set(xx) instead z.array(xx) if there is a `uniqueItems: true` found in a schema](https://github.com/astahmer/openapi-zod-client/blob/42100d199a1168dcb9e54317d2ae5a11bdc1b880/lib/tests/validations.test.ts#L36) ? but I'm not sure that would work at runtime for the zodios client, it needs investigation
- a cool feature would be to [auto-deduplicate error](https://github.com/astahmer/openapi-zod-client/issues/38) in a schema (with a var name auto infered from the operationId I guess)

**Closed** 2023-04-18 08:32 UTC
