### ISSUE TITLE
oneOf generates a wrong zod definition

### ISSUE THREAD

**Issue by misl-smlz** [astahmer/openapi-zod-client#104] opened 2023-03-27 12:41 UTC
When we create a zod client via `openapi-zod-client spec/openapi.json -o src/validation.ts` for the following [openapi.json](https://github.com/astahmer/openapi-zod-client/files/11078583/openapi.json.txt), it generates a wrong zod definition (`const TestObject = z.union([z.unknown(), z.unknown()])`).

Using **oneOf** in the [openapi.json](https://github.com/astahmer/openapi-zod-client/files/11078583/openapi.json.txt) leads to that error.

**Comment by astahmer** [comment] 2023-03-27 13:24
closing since it's a duplicate of https://github.com/astahmer/openapi-zod-client/issues/104
probably cause of today's github issues

**Closed by astahmer** 2023-03-27 13:24 UTC
